// <auto-generated />
using System;
using ConferenceRooms.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConferenceRooms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Booking_TotalPrice_NonNegative", "\"TotalPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsActive", "Capacity");

                    b.ToTable("Rooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Room_BaseHourlyRate_NonNegative", "\"BaseHourlyRate\" >= 0");

                            t.HasCheckConstraint("CK_Room_Capacity_Positive", "\"Capacity\" > 0");
                        });
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Services", null, t =>
                        {
                            t.HasCheckConstraint("CK_Service_Price_NonNegative", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("RoomService", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uuid");

                    b.HasKey("RoomId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("RoomServices", (string)null);
                });

            modelBuilder.Entity("ConferenceRooms.Domain.Entities.Booking", b =>
                {
                    b.OwnsMany("ConferenceRooms.Domain.Model.BookingRoom", "Rooms", b1 =>
                        {
                            b1.Property<Guid>("BookingId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Capacity");

                            b1.Property<DateTimeOffset>("EndAt");

                            b1.Property<decimal>("HourlyRate")
                                .HasPrecision(18, 2);

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<decimal>("RentalPrice")
                                .HasPrecision(18, 2);

                            b1.Property<Guid>("RoomId");

                            b1.Property<decimal>("ServicesPrice")
                                .HasPrecision(18, 2);

                            b1.Property<DateTimeOffset>("StartAt");

                            b1.Property<decimal>("TotalPrice")
                                .HasPrecision(18, 2);

                            b1.HasKey("BookingId", "__synthesizedOrdinal");

                            b1.ToTable("Bookings");

                            b1
                                .ToJson("RoomsSnapshot")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.OwnsMany("ConferenceRooms.Domain.Model.BookingService", "Services", b2 =>
                                {
                                    b2.Property<Guid>("BookingRoomBookingId");

                                    b2.Property<int>("BookingRoom__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<decimal>("Price")
                                        .HasPrecision(18, 2);

                                    b2.Property<Guid>("ServiceId");

                                    b2.HasKey("BookingRoomBookingId", "BookingRoom__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingRoomBookingId", "BookingRoom__synthesizedOrdinal");
                                });

                            b1.Navigation("Services");
                        });

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("RoomService", b =>
                {
                    b.HasOne("ConferenceRooms.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceRooms.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
